[package]
name = "bsq-rs"
version = "0.1.0"
authors = ["Philippe Loctaux <p@philippeloctaux.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.17"
rand = "0.7.3"

[[bin]]
name = "generator"
path = "src/generator.rs"

[[bin]]
name = "solver"
path = "src/solver.rs"